### ISSUE TITLE
Windows builds needed

### ISSUE THREAD

**Issue by astaric** [conda-forge/pymssql-feedstock#1]
I have noticed that the [conda-forge channel](https://anaconda.org/conda-forge/pymssql/files) does not include binaries for windows, while [defaults channel](https://anaconda.org/anaconda/pymssql/files) does.

Is there a plane to set up the windows build for the conda-forge channel as well? Is anyone working towards this?

**Comment by mariusvniekerk** [comment]
First place to start would be to make freetds windows builds. I don't currently have a windows machine to easily test this with.
