### ISSUE TITLE
New builds are failing

### ISSUE THREAD

**Issue by maresb** [conda-forge/pymssql-feedstock#19]
I don't know how to solve it, but hopefully I can save some time for someone who does...

Currently failing builds are #17 and #18.

The code triggering the failure is [here](https://github.com/pymssql/pymssql/blob/f587da9f2faed996616c17f3c1eeac7cbc8d0347/setup.py#L102-L111), namely that the `clock_gettime` could not be located.

I found a similar issue [here](https://github.com/uber/h3/issues/243#issuecomment-497453094). Namely,
> `clock_gettime` is in `glibc>=2.17` and in `librt` for `glibc<2.17`.

Unfortunately the configuration of C++ compilers and libraries is fairly mysterious to me.

In the context of macOS SDKs, the `clock_gettime` function is mentioned in [here in the conda-forge knowledge base](https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks).

Anyone have any ideas? :grinning:

**Comment by antkneed** [comment]
In order for the `setup.py` to find the correct compilers, [we had to call the](https://github.com/AnacondaRecipes/pymssql-feedstock/pull/3/files#diff-7d7b44a17a3ed98fbdb19179eb5d65ba250916e7db392883994f24ae9c4f4139) `distutils` function to customize them. This is done organically as a part of the normal `python setup.py build_ext`, but was not being done for the `has_function` check in `setup.py`.

Also, thanks for pointing out the MacOSX SDK version that has `clock_gettime`. 👍 

[Here](https://github.com/AnacondaRecipes/pymssql-feedstock/pull/3) is some work done if it is helpful.

**Comment by maresb** [comment]
Excellent, thank you very much @adipietro18 for the suggestions!

I don't know enough C++ to be able to make sense of this, but I'm wondering if it's possible/legal to just merge `meta.yaml` and `0002-customize_compiler.patch`? Any thoughts @mariusvniekerk?

**Comment by maresb** [comment]
Closed by #21
