### ISSUE TITLE
pymssql.org links to adult entertainment/recreation sites

### ISSUE THREAD

**Issue by ashwinsawant** [conda-forge/pymssql-feedstock#36]
### Comment:

The readme links to pymssql dot org, which provides the following examples of use:
- Utilized by well-known web and mobile applications including top adult sex dating sites (link to localsexapp dot com), adult entertainment platforms, e-commerce, etc.

- Flexability of the database interface illustrated in the development of the snap fuck (link to freefuckbook dot app) feature applied to free sex hookup apps (freefuckbook dot app) and adult chat platforms operated by FFB Networks.

Did someone prank the developer? Is this package safe to use?

**Comment by PrimozGodec** [comment]
This package is safe to use. Here is the repository of the package: https://github.com/pymssql/pymssql

I don't know what exactly happened, but it may be that someone bought the domain when developers didn't extend it anymore and abused the documentation. Here is the official link to the documentation: https://pymssql.readthedocs.io/en/latest/

I will fix the link in the recipe

**Comment by PrimozGodec** [comment]
It seems someone already reported it to developers https://github.com/pymssql/pymssql/issues/760
